"use client";

import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";

const DUMMY_THUMBNAILS = [
  {
    id: 1,
    url: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?q=80&w=600&auto=format&fit=crop",
    prompt: "Kids painting magically",
  },
  {
    id: 2,
    url: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=600&auto=format&fit=crop",
    prompt: "A beautiful animated island",
  },
  {
    id: 3,
    url: "https://images.unsplash.com/photo-1560088921-2a21fc7ba27a?q=80&w=600&auto=format&fit=crop",
    prompt: "Astronaut kid looking at the stars",
  },
  {
    id: 4,
    url: "https://images.unsplash.com/photo-1543332164-6e82f355badc?q=80&w=600&auto=format&fit=crop",
    prompt: "Colorful magic treehouse",
  },
  {
    id: 5,
    url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=600&auto=format&fit=crop",
    prompt: "A cute fluffy monster playing",
  },
  {
    id: 6,
    url: "https://images.unsplash.com/photo-1563200055-662f3a6a9b4d?q=80&w=600&auto=format&fit=crop",
    prompt: "Kids having a space adventure",
  },
];

export default function PublicGallery() {
  return (
    <div className="w-full max-w-6xl mx-auto px-4 pb-20">
      <div className="flex flex-col items-center justify-center text-center mb-12">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-100 mb-4 text-purple-700 font-bold border border-purple-200">
          <Sparkles className="w-4 h-4" /> Gallery
        </div>
        <h2 className="text-4xl md:text-5xl font-extrabold text-slate-800">
          See the Magic
        </h2>
        <p className="text-lg text-slate-500 font-medium mt-4 max-w-2xl">
          Discover some of the incredible 3D Pixar-style thumbnails generated by creators just like you. 
        </p>
      </div>
      
      <motion.div 
        className="grid grid-cols-2 md:grid-cols-3 gap-6"
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-100px" }}
        variants={{
          visible: { transition: { staggerChildren: 0.1 } },
          hidden: {}
        }}
      >
        {DUMMY_THUMBNAILS.map((item) => (
          <motion.div
            key={item.id}
            variants={{
              hidden: { opacity: 0, y: 20 },
              visible: { opacity: 1, y: 0 }
            }}
            whileHover={{ y: -5, scale: 1.02 }}
            className="group relative aspect-video rounded-3xl overflow-hidden glass-card shadow-lg hover:shadow-2xl transition-all"
          >
            <img 
              src={item.url} 
              alt={item.prompt} 
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
              loading="lazy"
            />
            
            {/* Hover overlay */}
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-end p-5">
              <p className="text-white text-base font-bold line-clamp-2 leading-tight drop-shadow-md">
                "{item.prompt}"
              </p>
            </div>
          </motion.div>
        ))}
      </motion.div>
    </div>
  );
}
